name: auto-pr-writer
description: Automatically generate PR descriptions using LLMs
author: Vladimir Blagojevic
branding:
  icon: edit-2
  color: blue
inputs:
  openai_api_key:
    description: OpenAI API key
    required: true
  openai_base_url:
    description: OpenAI Base URL
    required: false
    default: https://api.openai.com/v1
  github_token:
    description: GITHUB_TOKEN or a repo scoped PAT
    default: ${{ github.token }}
  github_repository:
    description: GitHub repository
    default: ${{ github.repository }}
  target_branch:
    description: Target branch
    default: ${{ github.event.pull_request.base.ref }}
  source_branch:
    description: Source branch
    default: ${{ github.event.pull_request.head.ref }}
  generation_model:
    description: LLM to use for PR text generation
    default: gpt-4-1106-preview
  system_prompt:
    description: System message/prompt to help the model generate the PR description
    required: false
  user_prompt:
    description: Additional prompt to help the model generate the PR description
    required: false
  bot_name:
    description: The name of the bot so users can guide LLM generation with @bot_name from PR comments
    default: auto-pr-writer-bot
  attribution:
    description: Attribution for the bot added in the footer of the PR description
    default: Generated by [Auto-PR-Writer](https://github.com/marketplace/actions/auto-pr-writer)

runs:
  using: 'docker'
  image: 'docker://vblagoje/auto-pr-writer:latest'
  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    OPENAI_BASE_URL: ${{ inputs.openai_base_url }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    GITHUB_REPOSITORY: ${{ inputs.github_repository }}
    BASE_REF: ${{ inputs.target_branch }}
    HEAD_REF: ${{ inputs.source_branch }}
    GENERATION_MODEL: ${{ inputs.generation_model }}
    AUTO_PR_WRITER_SYSTEM_MESSAGE: ${{ inputs.system_prompt }}
    AUTO_PR_WRITER_USER_MESSAGE: ${{ inputs.user_prompt }}
    AUTO_PR_WRITER_BOT_NAME: ${{ inputs.bot_name }}
    AUTO_PR_WRITER_ATTRIBUTION_MESSAGE: ${{ inputs.attribution }}
